# Generated by Django 5.0.1 on 2026-04-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_and_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityschedule',
            name='month_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityschedule',
            name='schedule_type',
            field=models.CharField(choices=[('daily', 'Harian'), ('weekly', 'Mingguan'), ('monthly', 'Bulanan')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='securityschedule',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='core.user'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='core.user'),
        ),
        migrations.AlterField(
            model_name='securityschedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityschedule',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_schedules', to='core.user'),
        ),
    ]
