# Generated by Django 5.0.1 on 2026-04-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_securityschedule_month_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('tidak aktif', 'Tidak Aktif')], default='aktif', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_personnel', to='core.rw')),
            ],
            options={
                'db_table': 'security_personnel',
            },
        ),
    ]
