# Generated by Django 5.0.1 on 2026-04-02 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_securitypersonnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityschedule',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.securitypersonnel'),
        ),
    ]
