# Generated by Django 5.0.1 on 2026-04-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_securityschedule_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityschedule',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
